# Generated by Django 3.2.5 on 2021-07-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postauthor',
            name='logo',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
