# Generated by Django 3.2.5 on 2021-07-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('description', models.TextField()),
                ('postcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.postcategory')),
            ],
        ),
    ]
