# Generated by Django 3.2.5 on 2021-07-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='description',
            field=models.TextField(blank=True, default='description'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='logo',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
