# Generated by Django 3.2.5 on 2021-07-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_comment_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='coment_id',
            new_name='comment_id',
        ),
    ]
