# Generated by Django 3.2.5 on 2021-07-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_coment_id_comment_comment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podpischiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
