# Generated by Django 3.2.5 on 2021-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('midle_name', models.CharField(blank=True, max_length=200)),
                ('rate1', models.IntegerField(blank=True, default=0)),
                ('rate2', models.IntegerField(blank=True, default=0)),
                ('rate3', models.IntegerField(blank=True, default=0)),
                ('rate4', models.IntegerField(blank=True, default=0)),
                ('rate5', models.IntegerField(blank=True, default=0)),
                ('rate_orta', models.FloatField(blank=True, default=0.0)),
                ('grup_name', models.CharField(blank=True, max_length=200)),
                ('birth_date', models.DateField(blank=True)),
                ('enter_date', models.DateField(blank=True)),
                ('course', models.IntegerField(blank=True, default=1)),
                ('faculty', models.CharField(blank=True, max_length=300)),
                ('citizenship', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
