# Generated by Django 3.2.5 on 2021-07-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_podpischiki_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('logo2', models.ImageField(blank=True, upload_to='upload')),
                ('description2', models.TextField(blank=True)),
                ('description3', models.TextField(blank=True)),
            ],
        ),
    ]
