# Generated by Django 3.2.5 on 2021-07-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_others'),
    ]

    operations = [
        migrations.RenameField(
            model_name='others',
            old_name='description',
            new_name='my_offered_services_desc',
        ),
        migrations.RenameField(
            model_name='others',
            old_name='description2',
            new_name='my_offered_services_title',
        ),
        migrations.RemoveField(
            model_name='others',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='others',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='others',
            name='logo2',
        ),
        migrations.RemoveField(
            model_name='others',
            name='title',
        ),
    ]
