# Generated by Django 3.2.5 on 2021-07-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210724_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='Clients_Feedback_About_Me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='Clients_Feedback_About_Me_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='Latest_Posts_From_Our_Blog',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='Latest_Posts_From_Our_Blog_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='Our_Latest_Featured_Projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='Our_Latest_Featured_Projects_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='choose_your_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='choose_your_plan_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='others',
            name='my_offered_services_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='others',
            name='my_offered_services_title',
            field=models.TextField(blank=True),
        ),
    ]
