# Generated by Django 3.2.5 on 2021-07-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210724_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='result',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='session',
            field=models.DateField(blank=True),
        ),
    ]
