# Generated by Django 3.2.5 on 2021-07-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_qualification_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='about_me_desc',
            field=models.TextField(blank=True),
        ),
    ]
