# Generated by Django 3.2.5 on 2021-07-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_others_footer_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='footer_follow_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='footer_follow_me_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='footer_newsletter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='footer_newsletter_desc',
            field=models.TextField(blank=True),
        ),
    ]
