# Generated by Django 3.2.5 on 2021-07-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210724_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='Frequently_Asked_Questions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='Frequently_Asked_Questions_desc',
            field=models.TextField(blank=True),
        ),
    ]
