# Generated by Django 3.2.5 on 2021-07-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210724_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='blog_newsletter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='blog_newsletter_desc',
            field=models.TextField(blank=True),
        ),
    ]
