# Generated by Django 3.2.5 on 2021-07-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210724_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='blog_newsletter_desc2',
            field=models.TextField(blank=True),
        ),
    ]
