# Generated by Django 3.2.5 on 2021-07-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_others_blog_newsletter_desc2'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='tag_clouds',
            field=models.TextField(blank=True),
        ),
    ]
