# Generated by Django 3.2.5 on 2021-07-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_others_tag_clouds'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='con_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='con_address_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='con_mail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='con_mail_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='con_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='others',
            name='con_number_desc',
            field=models.TextField(blank=True),
        ),
    ]
