# Generated by Django 3.2.5 on 2021-07-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210724_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='podpischiki',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='podpischiki',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='podpischiki',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
