# Generated by Django 3.2.5 on 2021-07-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desk', models.TextField(max_length=200)),
                ('capital', models.CharField(max_length=100)),
                ('square', models.IntegerField()),
            ],
        ),
    ]
