# Generated by Django 3.2.5 on 2021-07-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='desk',
            field=models.TextField(),
        ),
    ]
